#tomcat details.
server:
  port: 9292

# enable ansi output
spring:
  output:
    ansi:
      enabled: always

#actuator end points enable
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'