#tomcat details.
server:
  port: 9292


# enable ansi output
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/malpha?createDatabaseIfNotExist=true
    username: root
    password: Priyo123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #create-table will remain even also server shut-down,create-drop-will remove the db table once server restart done.Update-will remain with field data
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#actuator end points enable
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
#logging level
logging:
  level:
    org.springframework=DEBUG


